version: '3.9'


services:

  # App backend service
  app-server:
    container_name: app-server
    build:
      context: springboot-backend
      dockerfile: Dockerfile
    ports:
      - '${SPRING_LOCAL_PORT:?error}:${SPRING_DOCKER_PORT:?error}'
    restart: no
    depends_on:
      app-db:
        condition: service_healthy
    environment:
      DB_SCHEMA: $DB_SCHEMA
      DB_SERVER: app-db
      DB_DEFAULT_PORT: $DB_DOCKER_PORT
      DB_LOCAL_USER: $DB_DOCKER_USER
      DB_LOCAL_PASSWORD: $DB_DOCKER_PASSWORD
    networks:
      - backend
      - frontend

  # App frontend service
  app-client:
    container_name: app-client
    hostname: sun.klv.com # TODO: Change before deployment
    build:
      context: react-ui
      dockerfile: Dockerfile
    ports:
      - '${REACT_LOCAL_PORT:?error}:${REACT_DOCKER_PORT:?error}'
    restart: no
    depends_on:
      - app-server
    environment:
      REACT_SERVER: app-client
      SPRING_SERVER: app-server
    networks:
      - frontend

  # Database service (Mysql)
  app-db:
    container_name: app-db
    build:
      context: mysql-database
      dockerfile: Dockerfile
    ports:
      - '${DB_LOCAL_PORT:?error}:${DB_DOCKER_PORT:?error}'
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_SCHEMA
      MYSQL_USER: $DB_DOCKER_USER
      MYSQL_PASSWORD: $DB_DOCKER_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_DOCKER_ROOT_PASSWORD
    networks:
      - backend


volumes:
  db-data:


networks:
  backend:
  frontend: