x-defaults: &defaults
  env_file:
    - path: .env.example
      required: true
    - path: .env
      required: false

services:

  # App frontend service
  app-client:
    build:
      context: react-ui
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_DEFAULT_PORT:-3000}:${FRONTEND_DEFAULT_PORT:-3000}"
    restart: no
    depends_on:
      - app-server
    <<: *defaults
    environment:
      FRONTEND_SERVER: app-client
      BACKEND_SERVER: app-server
    networks:
      - frontend

  # App backend service
  app-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_DEFAULT_PORT:-8080}"
    restart: no
    depends_on:
      app-db:
        condition: service_healthy
    <<: *defaults
    environment:
      FRONTEND_SERVER: app-client
      DB_SERVER: app-db
    networks:
      - backend
      - frontend

  # Database service (Mysql)
  app-db:
    build:
      context: mysql-database
      dockerfile: Dockerfile
      args:
        DB_SCHEMA: ${MYSQL_DATABASE:-tsr_database}
    expose:
      - "${DB_DEFAULT_PORT:-3306}"
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
    <<: *defaults
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_ONETIME_PASSWORD: true
      MYSQL_INITDB_SKIP_TZINFO: true
    networks:
      - backend


volumes:
  db-data:


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
